
[misau_svr01]
192.168.200.33 hostname=svr01 ufw_private_interface=ens18

[misau_svr02]
192.168.200.34 hostname=svr02 ufw_private_interface=ens18

[misau_svr03]
192.168.200.35 hostname=svr03 ufw_private_interface=ens18

[misau_svr04]
192.168.200.36 hostname=svr04  ufw_private_interface=ens18

[misau_svr05]
192.168.200.37 hostname=svr05  ufw_private_interface=ens18

[misau_svr06]
192.168.200.38 hostname=svr06  ufw_private_interface=ens18

[misau_svr07]
192.168.200.39 hostname=svr07 ufw_private_interface=ens18 elasticsearch_node_name=es0 kafka_broker_id=0

[misau_svr08]
192.168.200.42 hostname=svr08 ufw_private_interface=ens18 elasticsearch_node_name=es1 kafka_broker_id=1

[misau_svr09]
192.168.200.40 hostname=svr09 ufw_private_interface=ens18 elasticsearch_node_name=es2 kafka_broker_id=2

[misau_svr10]
192.168.200.41 hostname=svr10 ufw_private_interface=ens18 elasticsearch_node_name=es3 


[control:children]
misau_svr01

[proxy:children]
misau_svr01

[webworkers:children]
misau_svr03
misau_svr04

[celery:children]
misau_svr03

[pillowtop:children]
misau_svr04

[django_manage:children]
misau_svr03

[formplayer:children]
misau_svr01

[rabbitmq:children]
misau_svr03

[couchdb2:children]
misau_svr05
misau_svr06

[couchdb2_proxy:children]
misau_svr01

[postgresql:children]
misau_svr06
misau_svr07

[pg_backup:children]
misau_svr08
misau_svr09

[pg_standby]


[shared_dir_host:children]
misau_svr04

[shared_efs_client_host:children]
pillowtop
celery
django_manage
webworkers
proxy

[redis:children]
misau_svr07

[zookeeper:children]
misau_svr01

[kafka:children]
misau_svr07
misau_svr08
misau_svr09

[elasticsearch:children]
misau_svr07
misau_svr08
misau_svr09
misau_svr10

